// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLa6XiIMcDQw7evZqqz4sMD117RSDiIb4',
    appId: '1:925775424206:web:05c15b2988e36f16417e9f',
    messagingSenderId: '925775424206',
    projectId: 'taskmate-7a681',
    authDomain: 'taskmate-7a681.firebaseapp.com',
    storageBucket: 'taskmate-7a681.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLa6XiIMcDQw7evZqqz4sMD117RSDiIb4',
    appId: '1:925775424206:web:05c15b2988e36f16417e9f',
    messagingSenderId: '925775424206',
    projectId: 'taskmate-7a681',
    storageBucket: 'taskmate-7a681.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLa6XiIMcDQw7evZqqz4sMD117RSDiIb4',
    appId: '1:925775424206:web:05c15b2988e36f16417e9f',
    messagingSenderId: '925775424206',
    projectId: 'taskmate-7a681',
    storageBucket: 'taskmate-7a681.firebasestorage.app',
    iosBundleId: 'com.example.taskmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLa6XiIMcDQw7evZqqz4sMD117RSDiIb4',
    appId: '1:925775424206:web:05c15b2988e36f16417e9f',
    messagingSenderId: '925775424206',
    projectId: 'taskmate-7a681',
    storageBucket: 'taskmate-7a681.firebasestorage.app',
    iosBundleId: 'com.example.taskmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLa6XiIMcDQw7evZqqz4sMD117RSDiIb4',
    appId: '1:925775424206:web:05c15b2988e36f16417e9f',
    messagingSenderId: '925775424206',
    projectId: 'taskmate-7a681',
    authDomain: 'taskmate-7a681.firebaseapp.com',
    storageBucket: 'taskmate-7a681.firebasestorage.app',
  );
}
